name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Deploy to PCF
      uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: ${{ secrets.CF_API }}
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: ${{ secrets.CF_ORG }}
        cf_space: ${{ secrets.CF_SPACE }}
        command: push -f manifest.yml